# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
    - r: 3.2
    - r: oldrel
    - r: release
    - r: devel
    - os: osx

matrix:
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: change
