# Welcome to Jekyll!

# Site variables -------
title: Shiny Reimagined With Bootstrap 4
email: nathanteetor@gmail.com
description: A new toolset to build shiny applications with Bootstrap 4.
baseurl: /dull
url: https://nteetor.github.io/

# Package variables ----
package:
  name: dull
  version: 0.0.5
  url: https://github.com/nteetor/dull

# Build settings -------
collections_dir: collections
markdown: kramdown
plugins:
  - jekyll-redirect-from

# Collections ----------
collections:
  content:
    output: yes
    permalink: /docs/0.0.5/:collection/:path
  utilities:
    output: yes
    permalink: /docs/0.0.5/:collection/:path
  inputs:
    output: yes
    permalink: /docs/0.0.5/:collection/:path
  layout:
    output: yes
    permalink: /docs/0.0.5/:collection/:path
  outputs:
    output: yes
    permalink: /docs/0.0.5/:collection/:path


# Defaults -------------
defaults:
- scope:
    path: ''
    type: content
  values:
    default_page: /docs/0.0.5/content/img
    sections:
    - name: img
      slug: img
    - name: blockquote
      slug: blockquote
    - name: pre
      slug: pre
- scope:
    path: ''
    type: utilities
  values:
    default_page: /docs/0.0.5/utilities/update-choices
    sections:
    - name: updateChoices
      slug: update-choices
    - name: font
      slug: font
    - name: background
      slug: background
    - name: border
      slug: border
    - name: rounded
      slug: rounded
    - name: float
      slug: float
    - name: affix
      slug: affix
    - name: display
      slug: display
    - name: padding
      slug: padding
    - name: width
      slug: width
    - name: showPopover
      slug: show-popover
    - name: flex
      slug: flex
    - name: sendModal
      slug: send-modal
    - name: tooltip
      slug: tooltip
    - name: markInvalid
      slug: mark-invalid
- scope:
    path: ''
    type: inputs
  values:
    default_page: /docs/0.0.5/inputs/text-input
    sections:
    - name: textInput
      slug: text-input
    - name: dateInput
      slug: date-input
    - name: rangeInput
      slug: range-input
    - name: selectInput
      slug: select-input
    - name: checkbarInput
      slug: checkbar-input
    - name: buttonInput
      slug: button-input
    - name: buttonGroupInput
      slug: button-group-input
    - name: checkboxInput
      slug: checkbox-input
    - name: dropdownInput
      slug: dropdown-input
    - name: groupInput
      slug: group-input
    - name: fileInput
      slug: file-input
    - name: formInput
      slug: form-input
    - name: listGroupThruput
      slug: list-group-thruput
    - name: radioInput
      slug: radio-input
- scope:
    path: ''
    type: layout
  values:
    default_page: /docs/0.0.5/layout/fieldset
    sections:
    - name: fieldset
      slug: fieldset
    - name: tabTabs
      slug: tab-tabs
    - name: column
      slug: column
    - name: formGroup
      slug: form-group
    - name: navbar
      slug: navbar
- scope:
    path: ''
    type: outputs
  values:
    default_page: /docs/0.0.5/outputs/sparkline-output
    sections:
    - name: sparklineOutput
      slug: sparkline-output
    - name: progressOutput
      slug: progress-output
    - name: streamOutput
      slug: stream-output


# Excluded files -------
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md