# Welcome to Jekyll!

# Site variables -------
title: A Reactive Web Framework Built on Shiny
email: nathanteetor@gmail.com
description: A new toolset to build shiny applications with Bootstrap 4.
    Includes refreshed reactive inputs, outputs, and new thruputs. Design
    utilities may be used to create responsive layouts for devices of all
    sizes.
baseurl: /yonder
url: https://nteetor.github.io/
versions: [0.0.5]

# Package variables ----
package:
  name: yonder
  version: 0.0.5
  url: https://nteetor.github.io/yonder

# Build settings -------
collections_dir: collections
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Excluded files -------
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md